### ISSUE TITLE
Missing IPv6 DNS Records for Domain Apex

### ISSUE THREAD

**Issue by juliaszone** [FossifyOrg/fossifyorg.github.io#5]
**Checklist**
 - [x] I can reproduce the bug on the website right now. 
 - [x] I made sure that there are no existing issues - open or closed - to which I could contribute my information to.
 - [x] I have read the FAQ and my problem isn't listed.
 - [x] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
 - [x] This issue contains only one bug.
 - [x] I have read and understood the [contribution guidelines.](https://github.com/FossifyOrg/General-Discussion?tab=readme-ov-file#faq)

**Describe the bug**
The Domain apex lacks AAAA records.

**To Reproduce**
`~ $ host fossify.org`
`fossify.org has address 185.199.111.153`
`fossify.org has address 185.199.108.153`
`fossify.org has address 185.199.109.153`
`fossify.org has address 185.199.110.153`
`fossify.org mail is handled by 10 mailstore1.secureserver.net.`
`fossify.org mail is handled by 0 smtp.secureserver.net.`

**Expected behavior**
The above output but with lines stating
`fossify.org has IPv6 address 2606:50c0:8000::153`
`fossify.org has IPv6 address 2606:50c0:8001::153`
`fossify.org has IPv6 address 2606:50c0:8002::153`
`fossify.org has IPv6 address 2606:50c0:8003::153`

**Screenshots**
Not applicable.

**Additional context**
Please make sure to always include IPv6 configuration as per https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain

**Comment by naveensingh** [comment]
![image](https://github.com/FossifyOrg/fossifyorg.github.io/assets/36371707/ab0ba59d-a455-4bcb-9353-45a25918933c)
